---
# play77--pa--nat-policy--firewall.yaml

- name: Play77 - Palo Alto Networks - Add NAT Policy to Firewall
#  vars:
#    hosts: grouppaloalto
  # Usage: Pass a valid host or a group on the command line via the argument 'hosts'.
  hosts: "{{ hosts }}"
  connection: __CONNECTION__TBD__
  collections:
    - paloaltonetworks.panos
  tasks:
    ####
    - name: T01 - Add the Service Object to the Firewall (Step 1/2)
      panos_service_object:
        provider: ""
        name: "service-tcp-221"
        protocol: "tcp"
        destination_port: "221"
        description: "SSH on port 221"
        commit: false
      register: out_add_svc_obj_firewall
    - name: T01-out
      debug:
        var: out_add_svc_obj_firewall.stdout_lines
    ####
    - name: T02 - Create Dynamic NAT Rule on the Firewall (Step 2/2)
      panos_nat_rule:
        provider: ""
        rule_name: "Web SSH inbound"
        source_zone: ["external"]
        destination_zone: "external"
        source_ip: ["any"]
        destination_ip: ["10.0.0.100"]
        service: "service-tcp-221"
        snat_type: "dynamic-ip-and-port"
        snat_interface: ["ethernet1/2"]
        dnat_address: "10.0.1.101"
        dnat_port: "22"
      register: out_add_nat_rule_firewall
    - name: T02-out
      debug:
        var: out_add_nat_rule_firewall.stdout_lines
    ####

...


# http://paloaltonetworks.github.io/ansible-pan/examples.html

