---
# play51--checkpoint-basic-config.yaml

- name: Play51 - Cisco - Capture Show Info Output
  #  vars:
  #    hosts: groupcisco
  # Usage: Pass a valid host or a group on the command line via the argument 'hosts'.
  hosts: "{{ hosts }}"
  gather_facts: no
  connection: network_cli
  tasks:
    ####
    - name: T01 - Show Info Command Sequence (Cisco) - run, ip route, ip eigrp neighbors, version
      ios_command:
        commands:
          - show run
          - show ip route
          - show ip eigrp neighbors
          - show version
        register: out_show_commands
    ####
    - name: T01-out - Save Output to Local Directory ./outdir-p51-t01/_inventory_hostname_.ios
      copy:
        content: "{{ out_show_commands.stdout | replace('\\n', '\n') }}"
      dest: "outdir-p51-t01/{{ inventory_hostname }}.ios"
    ####

...


# TODO: Test: Does the output directory need to pre-exist?  ./outdir-p51-t01/
#   This can be tested with any playbook so we don't need to wait for a device or an emulator.

# Source indicates this is for Cisco Routers but what about other Cisco devices?
#  All IOS versions?

# https://blog.noblinkyblinky.com/2020/10/26/capturing-show-output-with-ansible/

